### ISSUE TITLE
Error in B-tree

### ISSUE THREAD

**Issue by IarcaniusI** [Ashwin-op/B_and_Bplus_Tree#1]
There is a typo in the realization of B-tree.
It's necessary to change in file ```B-Tree.py``` in function ```_deletePredecessor``` line #193 from
```
return x.pop()
```
to
```
return x.keys.pop()
```

Since argument ```x``` is not a list of keys, it is an object-node that contains a list of keys.

**Comment by Ashwin-op** [comment]
Yeah, you're right!🤦 Thank you so much! 😉
